/**
 * Experiment: 30m/20min GF 50/80
 * 
 * Test 1: Full profile with 9m stop
 * Test 2: Skip 9m stop - does diver go below ceiling?
 */

import { 
    calculateTissueLoading,
    calculateCeilingTimeSeriesDetailed,
    N2_FRACTION
} from '../js/decoModel.js';

const gfLow = 0.5;
const gfHigh = 0.8;

// Profile WITH 9m stop (as generated by planner)
const waypointsWithStop = [
    { time: 0, depth: 0, gasId: "air" },
    { time: 2, depth: 30, gasId: "air" },
    { time: 20, depth: 30, gasId: "air" },
    { time: 23, depth: 9, gasId: "air" },   // Arrive at 9m
    { time: 24, depth: 9, gasId: "air" },   // 1 min stop at 9m
    { time: 25, depth: 6, gasId: "air" },   // Arrive at 6m
    { time: 26, depth: 6, gasId: "air" },   // 1 min stop at 6m
    { time: 27, depth: 3, gasId: "air" },   // Arrive at 3m
    { time: 30, depth: 3, gasId: "air" },   // 3 min stop at 3m
    { time: 31, depth: 0, gasId: "air" }    // Surface
];

// Profile WITHOUT 9m stop (skipping directly to 6m)
const waypointsSkip9m = [
    { time: 0, depth: 0, gasId: "air" },
    { time: 2, depth: 30, gasId: "air" },
    { time: 20, depth: 30, gasId: "air" },
    // SKIP 9m - go directly to 6m
    { time: 22.4, depth: 6, gasId: "air" },  // Arrive at 6m (ascent from 30m at 10m/min = 2.4 min)
    { time: 23.4, depth: 6, gasId: "air" },  // 1 min stop at 6m
    { time: 23.7, depth: 3, gasId: "air" },  // Arrive at 3m
    { time: 26.7, depth: 3, gasId: "air" },  // 3 min stop at 3m
    { time: 27, depth: 0, gasId: "air" }     // Surface
];

console.log('=== Experiment: 30m/20min GF 50/80 ===\n');

// Test 1: Profile WITH 9m stop
console.log('=== Test 1: Profile WITH 9m stop ===\n');
const results1 = calculateTissueLoading(waypointsWithStop, N2_FRACTION);
const { ceilingDepths: ceilings1, gfValues: gfs1, pAnchor: pAnchor1 } = calculateCeilingTimeSeriesDetailed(results1, gfLow, gfHigh);

console.log(`pAnchor: ${((pAnchor1 - 1) * 10).toFixed(2)}m`);
console.log('');
console.log('Time     | Depth  | Ceiling | GF     | Status');
console.log('---------|--------|---------|--------|--------');

let violations1 = [];
for (let i = 0; i < results1.timePoints.length; i++) {
    const t = results1.timePoints[i];
    const d = results1.depthPoints[i];
    const c = ceilings1[i];
    const gf = gfs1[i];
    
    // Only show key waypoints
    if (waypointsWithStop.some(wp => Math.abs(wp.time - t) < 0.01)) {
        const status = c > d ? '❌ VIOLATION' : '✓ OK';
        console.log(`${t.toFixed(1).padStart(8)} | ${d.toFixed(1).padStart(6)}m | ${c.toFixed(2).padStart(7)}m | ${(gf*100).toFixed(1).padStart(5)}% | ${status}`);
        if (c > d + 0.01) violations1.push({ t, d, c, excess: c - d });
    }
}

console.log('');
console.log(`Violations: ${violations1.length}`);
if (violations1.length > 0) {
    violations1.forEach(v => console.log(`  t=${v.t.toFixed(1)}: ceiling ${v.c.toFixed(2)}m > depth ${v.d.toFixed(1)}m by ${v.excess.toFixed(2)}m`));
}

// Test 2: Profile WITHOUT 9m stop
console.log('\n\n=== Test 2: Profile SKIPPING 9m stop ===\n');
const results2 = calculateTissueLoading(waypointsSkip9m, N2_FRACTION);
const { ceilingDepths: ceilings2, gfValues: gfs2, pAnchor: pAnchor2 } = calculateCeilingTimeSeriesDetailed(results2, gfLow, gfHigh);

console.log(`pAnchor: ${((pAnchor2 - 1) * 10).toFixed(2)}m`);
console.log('');
console.log('Time     | Depth  | Ceiling | GF     | Status');
console.log('---------|--------|---------|--------|--------');

let violations2 = [];
for (let i = 0; i < results2.timePoints.length; i++) {
    const t = results2.timePoints[i];
    const d = results2.depthPoints[i];
    const c = ceilings2[i];
    const gf = gfs2[i];
    
    // Show more detailed output during ascent
    if (t >= 20 && t <= 28) {
        const status = c > d ? '❌ VIOLATION' : '✓ OK';
        console.log(`${t.toFixed(2).padStart(8)} | ${d.toFixed(2).padStart(6)}m | ${c.toFixed(2).padStart(7)}m | ${(gf*100).toFixed(1).padStart(5)}% | ${status}`);
        if (c > d + 0.01) violations2.push({ t, d, c, excess: c - d });
    }
}

console.log('');
console.log(`Violations: ${violations2.length}`);
if (violations2.length > 0) {
    console.log('Ceiling violations detected:');
    violations2.slice(0, 10).forEach(v => console.log(`  t=${v.t.toFixed(2)}: ceiling ${v.c.toFixed(2)}m > depth ${v.d.toFixed(2)}m by ${v.excess.toFixed(2)}m`));
    if (violations2.length > 10) console.log(`  ... and ${violations2.length - 10} more`);
}

// Analysis
console.log('\n\n=== Analysis ===\n');
console.log('When skipping the 9m stop, the diver ascends directly from 30m to 6m.');
console.log('During this ascent, the diver passes through depths where ceiling > depth.');
console.log('');
console.log('The key question: Is the ceiling shown correctly during ascent?');
console.log('');

// Find the moment when diver is at 6m
const idx6m = results2.timePoints.findIndex(t => t >= 22.4 && results2.depthPoints[results2.timePoints.indexOf(t)] <= 6.1);
if (idx6m >= 0) {
    console.log(`At arrival at 6m (t=${results2.timePoints[idx6m].toFixed(2)}):`);
    console.log(`  Depth: ${results2.depthPoints[idx6m].toFixed(2)}m`);
    console.log(`  Ceiling: ${ceilings2[idx6m].toFixed(2)}m`);
    console.log(`  GF: ${(gfs2[idx6m]*100).toFixed(1)}%`);
    console.log(`  Ceiling > Depth? ${ceilings2[idx6m] > results2.depthPoints[idx6m] ? 'YES - VIOLATION!' : 'No'}`);
}
