/**
 * Narrated video walkthrough: a "▶ Video walkthrough" button that opens the video in
 * a modal dialog. The narration is English; subtitles start in the viewer's last
 * choice (first time: the UI language) and can be switched from the dialog bar.
 * Videos are generated by scripts/video/ as <base>.mp4 + <base>.jpg poster +
 * <base>.<lang>.vtt subtitle tracks.
 *
 * Usage (page markup, typically inside the hero):
 *   <div class="video-walkthrough" data-video-base="../videos/transfilling"></div>
 *
 *   import { initVideoWalkthroughs } from '../js/components/VideoWalkthrough.js';
 *   initVideoWalkthroughs();
 */
import { translate, getCurrentLanguage } from '../i18n.js';

/** Subtitle tracks, labelled in their own language. */
const SUBTITLES = [['en', 'English'], ['cs', 'Čeština']];
const STORAGE_KEY = 'decojs.videoSubtitles';

const LABELS = {
    open: ['common.video.open', '▶ Video walkthrough'],
    note: ['common.video.note', 'Narrated in English.'],
    subtitles: ['common.video.subtitles', 'Subtitles'],
    off: ['common.video.off', 'Off'],
    close: ['common.video.close', 'Close'],
};
const t = (name) => translate(...LABELS[name]);

let dialog = null;
let video = null;
let currentBase = null;
let currentSubtitles = 'off';

function preferredSubtitles() {
    try {
        const stored = localStorage.getItem(STORAGE_KEY);
        if (stored) return stored;
    } catch { /* storage blocked: fall back to the UI language */ }
    return getCurrentLanguage() === 'cs' ? 'cs' : 'en';
}

function setSubtitles(lang) {
    currentSubtitles = lang;
    for (const track of video.textTracks) track.mode = track.language === lang ? 'showing' : 'disabled';
    dialog.querySelectorAll('[data-sub]').forEach((b) => b.setAttribute('aria-pressed', String(b.dataset.sub === lang)));
    try { localStorage.setItem(STORAGE_KEY, lang); } catch { /* not persisted */ }
}

const choiceButtons = (cls) => [...SUBTITLES, ['off', '']].map(([lang, label]) =>
    `<button type="button" class="${cls}" data-sub="${lang}" aria-pressed="false">${label}</button>`).join('');

/** One shared dialog per page, created on first use. */
function ensureDialog() {
    if (dialog) return;
    dialog = document.createElement('dialog');
    dialog.className = 'video-dialog';
    dialog.innerHTML = `
        <div class="video-dialog-bar">
            <span class="video-dialog-note"></span>
            <span class="video-dialog-subs">
                <span class="video-dialog-subs-label"></span>
                ${choiceButtons('video-sub-btn')}
            </span>
            <button type="button" class="video-dialog-close">✕</button>
        </div>
        <video controls playsinline preload="none" width="1920" height="1080"></video>`;
    document.body.appendChild(dialog);
    video = dialog.querySelector('video');
    dialog.querySelectorAll('.video-sub-btn').forEach((b) =>
        b.addEventListener('click', () => setSubtitles(b.dataset.sub)));
    dialog.querySelector('.video-dialog-close').addEventListener('click', () => dialog.close());
    dialog.addEventListener('click', (e) => { if (e.target === dialog) dialog.close(); });
    dialog.addEventListener('close', () => video.pause());
    // The browser auto-enables a track of its own when the media loads; re-apply ours.
    video.addEventListener('loadedmetadata', () => setSubtitles(currentSubtitles));
    relabelDialog();
}

function relabelDialog() {
    if (!dialog) return;
    dialog.querySelector('.video-dialog-note').textContent = t('note');
    dialog.querySelector('.video-dialog-subs-label').textContent = `${t('subtitles')}:`;
    dialog.querySelectorAll('[data-sub="off"]').forEach((b) => { b.textContent = t('off'); });
    dialog.querySelector('.video-dialog-close').setAttribute('aria-label', t('close'));
}

function open(base) {
    ensureDialog();
    if (currentBase !== base) {
        currentBase = base;
        video.poster = `${base}.jpg`;
        video.src = `${base}.mp4`;
        video.querySelectorAll('track').forEach((tr) => tr.remove());
        for (const [lang, label] of SUBTITLES) {
            const track = document.createElement('track');
            Object.assign(track, { kind: 'subtitles', srclang: lang, label, src: `${base}.${lang}.vtt` });
            video.appendChild(track);
        }
    }
    setSubtitles(preferredSubtitles());
    dialog.showModal();
    video.play().catch(() => {});
}

function render(host) {
    host.innerHTML = '<button type="button" class="video-open-btn"></button>';
    host.querySelector('button').addEventListener('click', () => open(host.dataset.videoBase));
    relabel(host);
}

function relabel(host) {
    host.querySelector('.video-open-btn').textContent = t('open');
}

/** Render every `.video-walkthrough[data-video-base]` on the page. */
export function initVideoWalkthroughs() {
    const hosts = [...document.querySelectorAll('.video-walkthrough[data-video-base]')];
    hosts.forEach(render);
    document.addEventListener('languagechange', () => {
        hosts.forEach(relabel);
        relabelDialog();
    });
}
