/**
 * Narrated video walkthrough: a "▶ Video walkthrough" button (English video) plus a
 * smaller "CZ" button (Czech video), both opening the video in a modal dialog.
 * Videos are generated by scripts/video/ as <base>-en.mp4 / <base>-cs.mp4 with
 * .jpg posters next to them.
 *
 * Usage (page markup, typically inside the hero):
 *   <div class="video-walkthrough" data-video-base="../videos/transfilling"></div>
 *
 *   import { initVideoWalkthroughs } from '../js/components/VideoWalkthrough.js';
 *   initVideoWalkthroughs();
 */
import { translate } from '../i18n.js';

const LABELS = {
    open: ['common.video.open', '▶ Video walkthrough'],
    czech: ['common.video.czech', 'Czech version'],
    close: ['common.video.close', 'Close'],
    en: ['common.video.noteEn', 'Narrated in English, with captions.'],
    cs: ['common.video.noteCs', 'Narrated in Czech, with captions.'],
};

const t = (name) => translate(...LABELS[name]);

let dialog = null;
let video = null;
let note = null;
let playingLang = null;

/** One shared dialog per page, created on first use. */
function ensureDialog() {
    if (dialog) return;
    dialog = document.createElement('dialog');
    dialog.className = 'video-dialog';
    dialog.innerHTML = `
        <div class="video-dialog-bar">
            <span class="video-dialog-note"></span>
            <button type="button" class="video-dialog-close">✕</button>
        </div>
        <video controls playsinline preload="none" width="1920" height="1080"></video>`;
    document.body.appendChild(dialog);
    video = dialog.querySelector('video');
    note = dialog.querySelector('.video-dialog-note');
    const close = dialog.querySelector('.video-dialog-close');
    close.setAttribute('aria-label', t('close'));
    close.addEventListener('click', () => dialog.close());
    dialog.addEventListener('click', (e) => { if (e.target === dialog) dialog.close(); });
    dialog.addEventListener('close', () => video.pause());
}

function play(base, lang) {
    ensureDialog();
    const src = `${base}-${lang}.mp4`;
    if (video.getAttribute('src') !== src) {
        video.poster = `${base}-${lang}.jpg`;
        video.src = src;
    }
    playingLang = lang;
    note.textContent = t(lang);
    dialog.showModal();
    video.play().catch(() => {});
}

function render(host) {
    const base = host.dataset.videoBase;
    host.innerHTML = `
        <button type="button" class="video-open-btn" data-lang="en"></button>
        <button type="button" class="video-open-btn video-open-btn-small" data-lang="cs" lang="cs">CZ</button>`;
    host.querySelectorAll('button').forEach((btn) =>
        btn.addEventListener('click', () => play(base, btn.dataset.lang)));
    relabel(host);
}

function relabel(host) {
    host.querySelector('[data-lang="en"]').textContent = t('open');
    host.querySelector('[data-lang="cs"]').title = t('czech');
}

/** Render every `.video-walkthrough[data-video-base]` on the page. */
export function initVideoWalkthroughs() {
    const hosts = [...document.querySelectorAll('.video-walkthrough[data-video-base]')];
    hosts.forEach(render);
    document.addEventListener('languagechange', () => {
        hosts.forEach(relabel);
        if (dialog) {
            dialog.querySelector('.video-dialog-close').setAttribute('aria-label', t('close'));
            if (playingLang) note.textContent = t(playingLang);
        }
    });
}
